In [1]:
import numpy as np

In [2]:
lin=np.linspace(0,9,num=10)
lin

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
print(np.linspace(0,10,num=100,endpoint=False))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9 8.  8.1 8.2 8.3 8.4 8.5 8.6 8.7 8.8 8.9
 9.  9.1 9.2 9.3 9.4 9.5 9.6 9.7 9.8 9.9]


In [4]:
# 根据lambda的表达式结果创建一个数组
m=np.fromfunction(lambda x,y:(x+1)*(y+1),(9,9))
m

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

In [5]:
# ndarray 的数据类型
arr=np.array([1,2,3,4,5],dtype=np.float64)
arr

array([1., 2., 3., 4., 5.])

In [6]:
arr=np.array([1,2,3,'a'])
arr

array(['1', '2', '3', 'a'], dtype='<U11')

In [7]:
# 随机数组 0~150 形状(2,3)
np.random.randint(0,150,(2,3))

array([[  8,  62, 146],
       [ 88,  46, 116]])

In [8]:
# 产生指定形状随机数组，符合正态分布
np.random.randn(2,3,4)

array([[[ 1.37961679,  0.31530112, -1.54784423, -1.14339971],
        [ 0.48493429, -0.44450578, -0.82387313, -1.76235827],
        [-0.3655365 , -0.03202174, -0.54000095,  1.55194967]],

       [[-0.6620253 ,  0.83803525,  0.30310256,  0.55465271],
        [ 1.55907184, -0.73286112,  0.14417646, -1.03012907],
        [-2.07636578, -0.5128641 ,  0.40299469, -0.91717993]]])

In [9]:
arr=np.array([[1,2,3],[4,5,6]])
arr*2
np.add(arr,arr)
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [10]:
a1=np.random.randint(0,100,(2,3))
a2=np.random.randint(0,100,(3,2))
# 矩阵运算
np.dot(a1,a2)

array([[ 8791,  6418],
       [12917, 10296]])

In [11]:
arr=np.arange(0,10,0.2)
arr[[1,2]]=[23,43]
arr

array([ 0. , 23. , 43. ,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8])

In [12]:
arr=np.arange(0,10)
arr[0:8]
arr[::-1]
arr2=arr[1:4]
arr2[0:3]=1
arr

array([0, 1, 1, 1, 4, 5, 6, 7, 8, 9])

In [13]:
arr=np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])