一个.py可以说是一个module  
多个模块中需要调用使用import  
创建__init__.py  
from 包名 import 模块名

numpy  
用于科学计算和数据计算

In [1]:
import numpy as np

n维数组(ndarray)

In [2]:
arr = np.array([1,2,3,4])
print(arr,type(arr))
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr)

[1 2 3 4] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


ndarray中的属性  
shape:结构  
size:元素个数  

In [3]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr.size)
print(arr.shape)

6
(2, 3)


zeros,ones  
初始化数组  
zeros_like,ones_like  
将有值数组初始化，结构不变  
full(n,x)  
n为结构，填元组，x为充满的值

In [4]:
arr = np.zeros((2,3))
print(arr)
arr = np.ones((3,4))
print(arr)
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(np.ones_like(arr))
print(np.full((3,4),4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1]
 [1 1 1]]
[[4 4 4 4]
 [4 4 4 4]
 [4 4 4 4]]


linspace  
linspace(0,10,num = 100)   
0~10之间取100个等差的数  
num默认为50  
endpoint = True默认，表示右边范围为包含]的

In [5]:
arr = np.linspace(0,10,num = 10,endpoint = False)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


fromfunction  


In [6]:

arr = np.fromfunction(lambda x:x + 1,(10,))
print(arr)
print('\n')
arr = np.fromfunction(lambda x,y:(x + 1) * (y + 1),(9,9))
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 2.  4.  6.  8. 10. 12. 14. 16. 18.]
 [ 3.  6.  9. 12. 15. 18. 21. 24. 27.]
 [ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
 [ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
 [ 6. 12. 18. 24. 30. 36. 42. 48. 54.]
 [ 7. 14. 21. 28. 35. 42. 49. 56. 63.]
 [ 8. 16. 24. 32. 40. 48. 56. 64. 72.]
 [ 9. 18. 27. 36. 45. 54. 63. 72. 81.]]


ndarray可以指定数据类型  
传参dtype

In [7]:
arr = np.array([
    [1,2,3],
    [4,5,6],
],dtype = np.float64
)
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]]


np.sctypeDict  
查询numpy的数据类型

randint(n,m,(x,y))  
n~m结构为(x,y)的整数数组  
randn(x,y,z)  
结构为(x,y,z)的符合正态分布的数组  
uniform(n,m,(x,y))  
n~m结构为(x,y)的数组  

In [8]:
arr = np.random.randint(0,150,(2,3))
print(arr)
arr = np.random.randn(2,2,2)
print(arr)
arr = np.random.uniform(0,150,(2,3))
print(arr)

[[ 67 128 121]
 [ 70  11 141]]
[[[-1.05283713 -1.18883904]
  [ 1.34877348  2.82749932]]

 [[-0.10005726  1.99154015]
  [-1.16222656 -1.15102968]]]
[[104.29614023   3.07309068  81.74686091]
 [120.28120066  63.17588721 105.15974011]]


数组的计算

In [9]:
arr1 = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr1 * 2 - 1)
arr2 = np.array([
    [6,5,4],
    [3,2,1]
])
np.add(arr1,arr2)
print(arr1 * arr2)

[[ 1  3  5]
 [ 7  9 11]]
[[ 6 10 12]
 [12 10  6]]


矩阵运算  
np.dot

In [10]:
a1 = np.random.randint(0,100,(2,3))
a2 = np.random.randint(0,100,(3,2))
display(a1,a2)
np.dot(a1,a2)

array([[15, 52, 23],
       [75, 15, 35]])

array([[43, 81],
       [42, 19],
       [52, 27]])

array([[4025, 2824],
       [5675, 7305]])

np,arange()  
生成等差的数，可以为小数

In [11]:
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

索引

In [29]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[0][0])
print(arr[0][0:2])
print(arr[:2,:2])

1
[1 2]
[[1 2]
 [4 5]]
[4, 5, 6]
[[[1 2 3]
  [4 5 6]]]


bool索引

In [41]:
arr = np.array([
    [1,2,3],
    [1,2,1]
])
arr[arr == 1] = 5
print(arr)
arr = np.random.randn(2,3)
arr[arr < 0] = 0
print(arr)
arr = np.array([
    [1,2,3],
    [1,2,1]
])
arr[(arr == 1) | (arr == 2)] = 5
print(arr)

[[5 2 3]
 [5 2 5]]
[[0.         0.         0.        ]
 [2.29533914 0.         0.        ]]
[[5 5 3]
 [5 5 5]]


np.sum()  
axis = 1 计算横轴
axis = 0 计算数轴

In [49]:
arr = np.random.randint(1,10,(2,3))
np.sum(arr,axis = 1)
np.sum(arr,axis = 0)

array([ 8,  7, 11])

pandas  

In [53]:
import pandas as pd
from pandas import Series
from pandas import DataFrame

Series：带索引的一维数组  
可以加入index作为索引

In [ ]:
s = Series(['a','b','c','d'],index = [1,2,3,4])
print(s)
s = Series(np.arange(5),index = ['a','b','c','d','e'])
print(s)

1    a
2    b
3    c
4    d
dtype: object
a    0
b    1
c    2
d    3
e    4
dtype: int32
